### ISSUE TITLE
Successful build, but needed some adaptions

### ISSUE THREAD

**Issue by RobTS** [laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4#1]
Hi there, just wanted to report back a successful install with your work!

I had to change a few small details, though, I am unsure whether it is due to latest BIOS (7D43v17) having some changes or other reasons:

* There is a typo in the config.plist, `Contents/MacOS/IntelBTPatcher.kext` should be `Contents/MacOS/IntelBTPatcher`. BT Audio is still laggy, I suspect this one could be removed anyways, but have not tried yet.
* I needed to disable Secure Boot in BIOS for things to work.
* `SetupVirtualMap` needed to be `true` in my case, as otherwise it got stuck very early on in booting.
* I needed to compile my own `UTBMap.kext` within Windows to get any USB port recognized during install or use. You find it attached in case you want to compare.

Then again, compared what you had to go through, it is all small fry, I am very grateful you provided this repo and hope my remarks might help should you ever run into trouble with the build!

[UTBMap.kext.zip](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/files/9596692/UTBMap.kext.zip)

**Comment by laggykiller** [comment]
First of all, congrats for successful install!

> There is a typo in the config.plist, Contents/MacOS/IntelBTPatcher.kext should be Contents/MacOS/IntelBTPatcher.

Thank you for pointing out this mistake

> I needed to disable Secure Boot in BIOS for things to work.

Forgot that I had already disabled Secure Boot long before I work on hackintosh... Yes, It should be disabled and I should add this to `README`

> SetupVirtualMap needed to be true in my case, as otherwise it got stuck very early on in booting.

When using old BIOS, macOS boots successfully with `SetupVirtualMap` set as `false`. After I updated, it got stuck during early boot phase as you mentioned (`EB|LOG:EXITBS:START`). Hence I set `SetupVirtualMap` as `true` and it successfully boot. `config.plist` has been changed and a warning is placed at `README`

> I needed to compile my own UTBMap.kext within Windows to get any USB port recognized during install or use.

I have added a paragraph to your `UTBMap.kext` in `README` for others to test out

In response to this issue, a [commit](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/commit/5ac4aab0919a604b076e67f3ab941d40eea40b59) has been made

**Comment by dreamwhite** [comment]
> I needed to disable Secure Boot in BIOS for things to work.

Can I ask you the exact steps to follow in order to disable the Secure Boot?

**Comment by laggykiller** [comment]
@dreamwhite https://forum-en.msi.com/index.php?threads/secure-boot.366855/

**Comment by dreamwhite** [comment]
I feel a little bit confused. This guide is for enabling secure boot. and for disabling?

**Comment by laggykiller** [comment]
@dreamwhite Then choose Disable instead of Enable?

**Comment by dreamwhite** [comment]
Alright, I already tested with "Secure Boot" set to Disabled but still having the same issue. A working macOS Monterey 12.6.3 installer (already tested elsewhere) keeps me giving the same error "An error occurred while loading the update" around `12 minutes left` message on the progress bar

**Comment by laggykiller** [comment]
@dreamwhite please don't hijack this issue, comment on the issue you created
