### ISSUE TITLE
[Installation] An error occurred while loading the update

### ISSUE THREAD

**Issue by dreamwhite** [laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4#2]
Hi,
I'm trying since 7 days more or less installing macOS Monterey 12.6.3 using the full-installer method (`createinstallmedia` method from a macOS environment).
The installer correctly boots, and I'm able to format the disk and start the install, but whenever I reach the `12 minutes remaining...` loading screen in the first installation phase, I get this error.

From the installation log it seems like the files of the installer are corrupted somehow (at least from what I see in the installer log) BUT the same installer, tested multiple times before on other builds, works flawlessly.

At this point can be the Patriot P300 NVMe causing issues?

I wanna point out that I tested a slightly modified version of your EFI created by me that I attach below:

[EFI.zip](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/files/10804797/EFI.zip)

Thanks in advance

**Comment by laggykiller** [comment]
> I get this error.

What error?

> slightly modified version of your EFI

What was modified?

Unfortunately I am quite busy recently, so I cannot do much testing for you. I would advise you to use the EFI provided by this repo, and follow all advices in README. If you not sure if NVME is causing issue, you may try to install on another disk.

**Comment by dreamwhite** [comment]
> What error?

Sorry, I haven't attached the screenshot. Basically the error says `An error occurred while loading the update` when I reach the `12 minutes remaining...` loading progress bar

> What was modified?

I created the SSDTs from zero, as well as cleaned the config, and placed the kexts in a different order, that's all

**Comment by laggykiller** [comment]
A good way to debug is to use the EFI provided in my repo, then check if it is working on your setup. If working, then apply the changes you want, one by one.

**Comment by laggykiller** [comment]
Closing for stale issue and lack of information
