### ISSUE TITLE
Boot with stuck [EB|LOG:EXITBS:START]

### ISSUE THREAD

**Issue by kaseru** [laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4#4]
First of all, thank you very much for what you did.
I have a similar configuration as you suggested. But on startup I got the query. Here is my oc log. I used 1 efi from https://www.olarila.com/topic/25111-hackintosh-efi-folders-with-opencore-mod/ and installed it successfully. After installation. i copied your efi in and still got the same error as at first.

This my pc configuration
Motherboard: MSI PRO B660M-A WIFI DDR4
CPU: i7-12700
GPU: RX580 8G
RAM: DDR4 16GB (3200MHz)
SSD: Kingston 512 NVMe

And my config and log file

[opencore-2023-04-17-185732.txt](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/files/11254935/opencore-2023-04-17-185732.txt)
[config.txt](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/files/11254936/config.txt)

Pls help! Thanks!

**Comment by laggykiller** [comment]
I won't support Olarila installation. If you want support from me, please install again with vanilla image of MacOS and EFI of this repo, following my instructions in readme.

**Comment by kaseru** [comment]
Hi @laggykiller . I tried re-flashing the older bios. Your EFI has been booted in. But I have a problem Graphic Display 7M. Do you have any suggestions? My CPU: i7-12700 (Not F) and gpu RX580 8G.

**Comment by kaseru** [comment]
> 

Yes, I get it. But really, I had no other choice. I struggled with that problem for quite some time and many ways but it didn't work. I tried updating the older bios today and it worked but still problem with gpu.

**Comment by laggykiller** [comment]
Brand of GPU? Have you disabled iGPU in your EFI? Is HDMI/DP cable inserted to RX580 instead of motherboard?

I am just screening for common mistakes, if you still encounter problem, go debug yourself with dortania guide and google, or ask for support from orlarlia. You really should not mix orlarlia image with other stuff...

This may help you
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#polaris-10-and-20-series

**Comment by kaseru** [comment]
My gpu "AMD Radeon RX580 2048SP 8G". 
since downgraded bios and i can only use your efi.
I also add boot arg -wegnoigpu to disable igpu.
And make sure I have also plugged in the HDMI cable from the rx580 card.
Am I still missing something?

**Comment by kaseru** [comment]
My GPU Polaris 20. Graphic card "AMD Radeon RX 580 2048SP" Brand MSI.
I'm pretty sure I plugged in the hdmi cap from the rx 580 card.
I also added the boot arg  "-wegnoigpu" to disable igpu.
Since downgrading bios and booting from your efi. I no longer use efi from any other source an everything seems to work perfectly except the gpu
If there are more suggestions. Please tell me. Thank you!

**Comment by laggykiller** [comment]
RX580 2048SP is actually not RX580. It is RX570 flashed with special vBIOS.

You will need to flash vBIOS of RX570. There is risk of bricking your card. Go google it and good luck.

**Comment by kaseru** [comment]
> 
I actually did it that way and it worked. Very thanks!
