### ISSUE TITLE
i need msi PRO B650-P WIFI 's EFI. where can I find it? 

### ISSUE THREAD

**Issue by mumin16** [laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4#6]
i need msi PRO B650-P WIFI 's EFI. where can I find it?

**Comment by laggykiller** [comment]
MSI PRO B650-P is motherboard for AMD CPU, while B660M is for Intel CPU. If you can't find it with google, then make the EFI yourself by reading https://dortania.github.io/OpenCore-Install-Guide/ instead of asking on a repo that is not relevant.
